### ISSUE TITLE
Custom Viewholder implementation

### ISSUE THREAD

**Issue by nowke** [kanytu/android-parallax-recyclerview#15]
I'm having mu custom viewholder which extends RecyclerView.ViewHolder and I'm dynamically updating the recyclerview. It's showing error while Overriding onBindViewHolder. I have used an Interface 'AccountInfo' instead of 'String' type. 

Here's my Adapter code:

    public class AccountDetailAdapter extends ParallaxRecyclerAdapter<AccountDetailAdapter.AccountDetailViewHolder> {

      private LayoutInflater inflater;
      private Context context;

      List<AccountInfo> data = Collections.emptyList();

      public AccountDetailAdapter(Context context, final List<AccountInfo> data) {
        super(new ArrayList<AccountInfo>());
        this.context = context;
        inflater = LayoutInflater.from(context);
        this.data = data;
        implementRecyclerAdapterMethods(new RecyclerAdapterMethods() {

            @Override
            public void onBindViewHolder(AccountDetailViewHolder viewHolder, int i) {
                AccountInfo current = data.get(i);
                viewHolder.pName.setText(current.personName);
                viewHolder.pBalance.setText(current.personBalance);
                viewHolder.pIcon.setImageDrawable(current.personIconId);
            }

            @Override
            public AccountDetailViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
                View view = inflater.inflate(R.layout.account_row, viewGroup, false);
                AccountDetailViewHolder holder = new AccountDetailViewHolder(view);
                return holder;
            }

            @Override
            public int getItemCount() {
                return data.size();
            }
         });
      }

       class AccountDetailViewHolder extends RecyclerView.ViewHolder {
    
            TextView pName;
            TextView pBalance;
            ImageView pIcon;
    
            public AccountDetailViewHolder(View itemView) {
                super(itemView);
    
                pName = (TextView) itemView.findViewById(R.id.personName);
                pBalance = (TextView) itemView.findViewById(R.id.personBalance);
                pIcon = (ImageView) itemView.findViewById(R.id.personIconId);
                itemView.setClickable(true);
            }
    
        }
    }

And in calling super(new ArrayList<AccountInfo>()), it says "ParallaxRecyclerAdapter (java.util.List<com.example.myapp>.AccountDetailAdapter.AccountDetailViewHolder) in ParallaxRecyclerAdapter cannot be applied to java.util.ArrayList<com.example.myapp>.AccountInfo.

![selection_004](https://cloud.githubusercontent.com/assets/5479836/7026297/92987c60-dd66-11e4-938a-2204a7915373.png)

How do I port to my own ViewHolder?

**Comment by kanytu** [comment]
Does this code work for you?


    public AccountDetailAdapter(Context context, final List<AccountInfo> data) {
        super(new ArrayList<AccountInfo>());
        this.context = context;
        inflater = LayoutInflater.from(context);
        this.data = data;
        implementRecyclerAdapterMethods(new RecyclerAdapterMethods() {
            
            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
                AccountInfo current = data.get(i);
                viewHolder.pName.setText(current.personName);
                viewHolder.pBalance.setText(current.personBalance);
                viewHolder.pIcon.setImageDrawable(current.personIconId);
            }

            @Override
            public AccountDetailViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
                View view = inflater.inflate(R.layout.account_row, viewGroup, false);
                AccountDetailViewHolder holder = new AccountDetailViewHolder(view);
                return holder;
            }
    
            @Override
            public int getItemCount() {
                return data.size();
            }
         });
      }
    
       class AccountDetailViewHolder extends RecyclerView.ViewHolder {
    
            TextView pName;
            TextView pBalance;
            ImageView pIcon;
    
            public AccountDetailViewHolder(View itemView) {
                super(itemView);
    
                pName = (TextView) itemView.findViewById(R.id.personName);
                pBalance = (TextView) itemView.findViewById(R.id.personBalance);
                pIcon = (ImageView) itemView.findViewById(R.id.personIconId);
                itemView.setClickable(true);
            }
    
        }

**Comment by nowke** [comment]
Yes. But since it has no members pName, pIcon, pBalance, it shows error in viewholder.pName, viewholder.pBalance inside onBindViewHolder.

**Comment by kanytu** [comment]
That's because you need to cast it:

            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder viewHolder, int i) {
                AccountInfo current = data.get(i);
                AccountDetailViewHolder holder = (AccountDetailViewHolder) viewHolder;
                holder.pName.setText(current.personName);
                holder.pBalance.setText(current.personBalance);
                holder.pIcon.setImageDrawable(current.personIconId);
            }

**Comment by nowke** [comment]
Thanks! That error is gone. But super(new ArrayList<AccountInfo>()); still shows error. Is it problem with ArrayList and List? I'm not getting it.

![selection_004](https://cloud.githubusercontent.com/assets/5479836/7027666/5f188f80-dd6e-11e4-9bac-a1e58356177e.png)

**Comment by kanytu** [comment]
Have you changed your 
    public class AccountDetailAdapter extends ParallaxRecyclerAdapter<AccountInfo> {
?

Because I changed the code after I posted the answer. The class declaration needs to be changed too.

**Comment by nowke** [comment]
Oh sorry! Didn't see that. Thanks a lot! Closing issue.
