### ISSUE TITLE
Fading Actionbar with FAB

### ISSUE THREAD

**Issue by qnitesh** [kanytu/android-parallax-recyclerview#16]
Hi,
How to achieve this layout?
[bit.ly/1CKRIQM] (bit.ly/1CKRIQM)

**Comment by wardellchandler** [comment]
Bump. I'm also trying to figure this out, using https://github.com/makovkastar/FloatingActionButton. 

I don't know what picture @qnitesh posted, but I'd like to get the FAB to stick to the seam between the header and the list items, and I'm having some difficulties doing that. 

Is this possible?

**Comment by kanytu** [comment]
He posted this:
https://1.bp.blogspot.com/-n1_hHrKdUFo/VLyVCHXxJsI/AAAAAAAAAF0/U0KEnRDCx7I/s1600/animColor2.gif

It is possible but it will require some math to acquire..

First you will have to use onParallaxScroll listener for that.

I will describe the though of process in a very raw manner hoping you guys understand it:

- get height of header (headerSize)
- get height of fab (fabSize)
- get rec of recyclerView size (recyclerRect)
- implement  onParallaxScroll
- on onParallaxScroll position fab on the recyclerRect.top + (headerSize -onParallaxScroll.offset) - fabSize/2 and aligned right to the parent (which should be a relative layout obviously)
- add a check to see if onParallaxScroll.offset -fabSize/2  == headerSize (which means that the fab is at the top of the view) and set it to bottom

**Comment by qnitesh** [comment]
@wardellchandler If you are successfully able to construct the layout, please do post'em here. I'll try to follow the above method.

**Comment by wardellchandler** [comment]
@kanytu One note: The check should be greater than or equal to headerSize, but othewise, this worked flawlessly. Thanks a ton.

@qnitesh 

This is the layout for my fragment. 

```xml
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:fab="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.github.ksoichiro.android.observablescrollview.ObservableRecyclerView
        android:id="@+id/profile_recycler_view"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="center_horizontal|top"
        android:orientation="vertical"
        android:weightSum="2" />

    <com.melnykov.fab.FloatingActionButton
        android:id="@+id/fab"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@drawable/ic_search_white_24dp"
        fab:fab_colorNormal="?colorAccent"
        fab:fab_colorPressed="?colorAccent"
        fab:fab_colorRipple="?colorPrimaryDark"
        android:layout_margin="50dp"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true" />
</RelativeLayout>
```
  
This is what I set for be the header. 
```xml
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout
    android:layout_width="fill_parent"
    android:layout_height="200dp"
    android:layout_gravity="center_horizontal"
    android:background="?colorPrimary"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:fab="http://schemas.android.com/apk/res-auto">

    <ImageView
        android:id="@+id/profile_picture"
        android:layout_width="fill_parent"
        android:layout_height="200dp"
        android:background="#FFFFFF"
        android:cropToPadding="true"
        android:scaleType="centerCrop"
        android:src="@drawable/person" />
</RelativeLayout>
```

The actual code is just as @kanytu said though, but I'll go ahead and put that here, too. It isn't perfect (I haven't edited the code to properly position it at the bottom, just to throw it there) but it does work. 

```java
        final ViewGroup header = (ViewGroup) inflater.inflate(R.layout.profile_header, recyclerView, false);
        ((ImageView) header.findViewById(R.id.profile_picture)).setImageBitmap(picture);
        final FloatingActionButton fab = (FloatingActionButton) rootView.findViewById(R.id.fab);
        stringAdapter.setParallaxHeader(header, recyclerView);
        stringAdapter.setOnParallaxScroll(new ParallaxRecyclerAdapter.OnParallaxScroll() {
            @Override
            public void onParallaxScroll(float percentage, float offset, View view) {
                int headerHeight = header.getHeight();
                int fabHeight = fab.getHeight();
                Rect recyclerRect = new Rect(0, 0, 0, 0);
                recyclerView.getDrawingRect(recyclerRect);

                if (offset - fabHeight / 2 >= headerHeight) {
                    fab.setY(recyclerRect.bottom - fabHeight);
                } else {
                    fab.setY(recyclerRect.top + (headerHeight - offset) - fabHeight / 2);
                }
            }
        });
```

**Comment by kanytu** [comment]
Yes @qnitesh you're right. It should be greater than or equal instead of just equal. Glad you figured it out :) I will probably use some of your code if I decide to create a readme with how to do that effect.

**Comment by anujkalal** [comment]
I am using different heights of recyclerview tupple.I am not able to use pagination with items and onscrolling from bottom to up then headerView move to exact location. Please provide me solution
