### ISSUE TITLE
The header height is really small and I don't see any config for this.

### ISSUE THREAD

**Issue by ChristopheVersieux** [kanytu/android-parallax-recyclerview#17]
Hello all,

I sucessfully imported your awesome lib, and nearly everything is working fine:

I have added a Google Map (Lite mode) in my header xml, like this:

<?xml version="1.0" encoding="utf-8"?>
<fragment xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:map="http://schemas.android.com/apk/res-auto"
    android:id="@+id/map"
    android:name="com.google.android.gms.maps.MapFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    map:liteMode="true"
    map:mapType="normal" />

and the current rendering is horrible: the map is too small:

I have tried to play by whanging every height I could, but the small header is really annoying and I don't see any option to change it.

![screenshot_2015-05-11-22-28-58](https://cloud.githubusercontent.com/assets/356214/7574380/353122c0-f82d-11e4-9003-c1af2a01d99e.png)

**Comment by kanytu** [comment]
Have you tried wrapping the map inside a relative layout or something like that with a fixed height?

**Comment by ChristopheVersieux** [comment]
Yes, I tried a RelativeLayout match_parent like your example 
https://github.com/kanytu/example-parallaxrecycler/blob/master/app/src/main/res/layout/my_header.xml

**Comment by ChristopheVersieux** [comment]
OK, match parent was not working, a fixed height in dp is OK.
Thank a lot!
