### ISSUE TITLE
First item unknown.

### ISSUE THREAD

**Issue by marko-lazic** [kanytu/android-parallax-recyclerview#23]
However i implement it, i always get first item empty.

**Comment by marko-lazic** [comment]
Basically i get first cardview empty, and then it populate rest of the cards with acutal data.

**Comment by marko-lazic** [comment]
With layoutManagerFixed.setReverseLayout(true); it is now floating someware behind at the bottom.

**Comment by kanytu** [comment]
Show me your current code.

**Comment by marko-lazic** [comment]
https://github.com/marko-lazic/Goropadnica/blob/master/app/src/main/java/net/markoslab/goropadnica/activities/ClientDetailActivity.java

https://github.com/marko-lazic/Goropadnica/blob/master/app/src/main/res/layout/activity_client_detail.xml

**Comment by marko-lazic** [comment]
https://goo.gl/photos/mWWSg1BS98hN7XCN8

**Comment by marko-lazic** [comment]
Forgot to mention, that i am running everything on latest version in build.gradle. Could that be it?

**Comment by kanytu** [comment]
there is no implementation of the parallax header in this code
