### ISSUE TITLE
Parallax header bug inside viewpager

### ISSUE THREAD

**Issue by bdaykid** [kanytu/android-parallax-recyclerview#25]
Hi, I've put the recyclerview with parallax header inside a viewpager which have 4 fragment (0 - 3). The problem occurs when the recyclerview is scrolled until the image collapsed, then the viewpager change position from 0 - 2. When i return back to the fragment (position 0) and scrolled back up the image are gone (white blank).  

I set the adapter.setParallaxHeader() inside the onCreateView. Is this a bug or am i putting it in the wrong place? Thank you.

**Comment by bdaykid** [comment]
Solved already. Sorry for the rush posting this. Just set the button and onClick as usual.

**Comment by kanytu** [comment]
In fact it's a strange use case. Are you reloading the adapter when you swipe back to your list?

**Comment by bdaykid** [comment]
The viewpager automatically reloads the fragment containing the parallaxheader. If the parallaxheader is visible before i swipe, it will still reload but the header is loaded back again. Unless i scroll down till the header is gone, then it will be blank if i swipe to the other fragment. I'm guessing its the issue of scrolling position, the state is not saved. If u need to see any code i can post here, but a bit late because i'm not at my desk. Thank you so much for your response!

**Comment by bdaykid** [comment]
@kanytu I found a workaround for now. I changed the viewpager offscreenpagelimit, so it wont destroy the fragment containing the parallaxheader when the viewpager is swiped. Thank you.
