### ISSUE TITLE
ParallaxRecyclerAdapter implements RecyclerAdapterMethods

### ISSUE THREAD

**Issue by bryant1410** [kanytu/android-parallax-recyclerview#26]
Wouldn't it be more appropriate if instead of having a method that asks for the implementation, to have them overriden?

I mean, instead of this:

```java
ParallaxRecyclerAdapter<String> adapter = new ParallaxRecyclerAdapter<>(content);
adapter.implementRecyclerAdapterMethods(new ParallaxRecyclerAdapter.RecyclerAdapterMethods() {
    // implemented methods
}
```

This:

```java
ParallaxRecyclerAdapter<String> adapter = new ParallaxRecyclerAdapter<>(content) {
    // implemented methods
}
```

**Comment by kanytu** [comment]
You're suggesting an abstract class?

**Comment by bryant1410** [comment]
Yes

**Comment by kanytu** [comment]
Added in last commit

**Comment by bryant1410** [comment]
There are some caveats in my opinion.

Why is ViewHolder inherited? It's not adding anything.

The class also enforces to use a list and methods of handling the items, which I think goes beyond the scope of this library, which may be to provide header and parallax effect.

Consider the PR in #31

**Comment by kanytu** [comment]
The class doesn't enforce to set other listeners/methods than the original ones of the recycler adapter.

It's meant to be simple and easy to implement

**Comment by bryant1410** [comment]
Yeah it simple, but:
* Enforces to use a list.
* Handles adding items, removing items, getting and setting in a list, which I think it's ok for a project (and commonly used in adapters), but not for a library which is supposed to be generic
* ViewHolder class adds nothing
* It messes with item on click listener, which is out of the adapter's responsibilities
* Also I think the header must be mandatory, not optional, otherwise the library doesn't make sense

**Comment by kanytu** [comment]
Enforcing it to use a list just makes it simpler. If you need a more advanced and generic library this is not the place.
My viewholder adds as much as your two HeaderViewHolder and ItemViewHolder.
If you don't use setOnClickEvent then there is no mess.
The header being mandatory disallows people with adapters that already have an header to remove it.
