### ISSUE TITLE
Wrong package name

### ISSUE THREAD

**Issue by bryant1410** [kanytu/android-parallax-recyclerview#27]
HeaderLayoutManagerFixed and ParallaxRecyclerAdapter declare their package to be com.poliveira.parallaxrecycleradapter, but they are in the folder com.poliveira.parallaxrecyclerview. Which is right?

**Comment by kanytu** [comment]
The right one is the ParallaxRecyclerAdapter package. Will have to fix it later

**Comment by bryant1410** [comment]
Opened a PR in #29 about this
