### ISSUE TITLE
Error when I try to import the library

### ISSUE THREAD

**Issue by max02100** [kanytu/android-parallax-recyclerview#34]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.github.kanytu:android-parallax-recyclerview:v1.3.
     Searched in the following locations:
         https://jcenter.bintray.com/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.pom
         https://jcenter.bintray.com/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.jar
         file:/C:/Users/Maxime/AppData/Local/Android/sdk/extras/android/m2repository/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.pom
         file:/C:/Users/Maxime/AppData/Local/Android/sdk/extras/android/m2repository/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.jar
         file:/C:/Users/Maxime/AppData/Local/Android/sdk/extras/google/m2repository/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.pom
         file:/C:/Users/Maxime/AppData/Local/Android/sdk/extras/google/m2repository/com/github/kanytu/android-parallax-recyclerview/v1.3/android-parallax-recyclerview-v1.3.jar
     Required by:
         mytripeazzy:app:unspecified

**Comment by kanytu** [comment]
Could you post your gradle file?

**Comment by max02100** [comment]
This is my gradle file with the import from in the repositories : 
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
    }
}
apply plugin: 'com.android.application'

repositories {
    jcenter()
}

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "com.mvince.mytripeazzy.app"
        minSdkVersion 16
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.google.android.gms:play-services:7.0.0'
    compile 'com.android.support:appcompat-v7:21.0.2'
    compile 'com.android.support:support-v4:21.0.2'
    compile 'com.android.support:cardview-v7:21.0.2'
    compile 'com.android.support:recyclerview-v7:21.0.2'
    compile 'com.getbase:floatingactionbutton:1.9.1'
    compile 'de.hdodenhof:circleimageview:1.2.1'
    compile 'com.android.support:recyclerview-v7:21.0.2'
    compile 'com.github.traex.rippleeffect:library:1.2.3'
    compile 'com.google.code.gson:gson:2.2.4'
    compile 'com.afollestad:material-dialogs:0.7.4.2'
    compile 'com.facebook.android:facebook-android-sdk:3.23.1'
    compile 'com.sothree.slidinguppanel:library:3.0.0'
    compile 'it.neokree:MaterialTabs:0.11'
    compile 'com.edmodo:rangebar:1.0.0'
    compile 'com.android.support:design:22.2.0'
    compile 'com.iangclifton.android:floatlabel:1.0.4'
    compile 'com.github.paolorotolo:appintro:3.2.0'
    compile 'com.github.kanytu:android-parallax-recyclerview:v1.3'
}

**Comment by kanytu** [comment]
Could you try following this tutorial?

https://jitpack.io/#kanytu/android-parallax-recyclerview/v1.3

**Comment by kanytu** [comment]
I think you're putting maven {url "https://jitpack.io"} in the wrong repository place.

**Comment by max02100** [comment]
Indeed!! it was in the wrong repositories :/ 

Thanks for your help and for the lib, it will be helpfull!
