### ISSUE TITLE
setOnClickEvent() never called

### ISSUE THREAD

**Issue by shineangelic** [kanytu/android-parallax-recyclerview#35]
I simply want to detect clicks over parallaxAdapter items.

Maybe I'm missing something, I can't get setOnClickEvent() to work.

   mAdapter.setOnClickEvent(new ParallaxRecyclerAdapter.OnClickEvent() {
            @Override
            public void onClick(View view, int i) {
               //This is never called
            }
        });

Please note that mAdapter.setOnParallaxScroll(new ParallaxRecyclerAdapter.OnParallaxScroll() ... ) works perfectly and I have onBindViewHolderImpl(), onCreateViewHolderImpl(), etc. implemented and working inside the adapter impl

**Comment by shineangelic** [comment]
BTW I am quite sure the code was working in previous lib version. Now I'm using v1.3

**Comment by kanytu** [comment]
Hum. I'll take a look at it tomorrow. That should be easy to fix.

**Comment by kanytu** [comment]
This should be fixed on v1.4

Thanks for your report :)

**Comment by shineangelic** [comment]
yes, I confirm it's working now. Thank you for support
