### ISSUE TITLE
First Item indeterminate, especially with no header.

### ISSUE THREAD

**Issue by s73v3r** [kanytu/android-parallax-recyclerview#36]
I have a situation where I may or may not have a header. When I have a header, everything is fine. However, if I don't have a header, then things get strange. 

onBindViewHolder() will not call my onBindViewHolderImpl() if the position is 0. However, onCreateViewHolderImpl() will still be called, expecting a ViewHolder to be created. The two methods have differing expectations. 

There should be a consistent flow of events. You should either always handle position 0, regardless of if there's a header, or you should handle it if there is a header, and pass through like a regular RecyclerAdapter if not.

**Comment by stevemalsam** [comment]
Created pull request #37 to address this issue.
