### ISSUE TITLE
Add another header

### ISSUE THREAD

**Issue by bdaykid** [kanytu/android-parallax-recyclerview#40]
Hello. Want to know, can i add another header? a header that is not inside the parallax header. Where should i do that. Thank you.

**Comment by kanytu** [comment]
So you basically want two headers? Why not use a ViewGroup as your header and add both inside it?

**Comment by bdaykid** [comment]
Won't the second header get the parallax effect too? I just want the first header to have parallax effect. But I'll try anyway.

**Comment by kanytu** [comment]
Yes it will. I know what you want. Basically you want a different type of view for the first item. So you want the first item of the list to have parallax effect, the second to be a header with no parallax and finally the list items. Am I correct?

**Comment by bdaykid** [comment]
Yes. Absolutely correct. Maybe can add this as a new feature in your lib. Would be great! :)

**Comment by kanytu** [comment]
no need to. That's already available on the framework. Take a look at https://github.com/kanytu/android-parallax-recyclerview/issues/10 for example. You need to change  getItemViewTypet to return a different type of id. Then on oncreateviewholder, inflate a different viewholder accordingly to the view type
