### ISSUE TITLE
Modify header in runtime

### ISSUE THREAD

**Issue by facundomedica** [kanytu/android-parallax-recyclerview#42]
I want to change something that is inside my header layout (an Image View alpha) during scroll (just like he toolbar alpha thing). Is this possible?

**Comment by kanytu** [comment]
Yes it is.

Just implement `onParallaxScroll(float percentage, float offset, View parallax);`

Then inside it change your parallax view (3rd parameter of onParallaxScroll) alpha to whatever you want. Hint: you can use percentage to calculate an alpha between 0 and 1 :)

**Comment by facundomedica** [comment]
I missed that completely! But what I really need is to get a Linear Layout that is inside the parallax view. (I'm quite a noob in Android and java)
Thanks!

**Comment by facundomedica** [comment]
Found it!
I leave this here if any noob pass by looking for the same as I did
```
parallax.findViewById(R.id.myLinear).setAlpha(...);
```
