### ISSUE TITLE
Getting percentage (and offset) wrong

### ISSUE THREAD

**Issue by facundomedica** [kanytu/android-parallax-recyclerview#43]
The problem is quite simple to explain, but I don't know how to solve it...
-> When I start scrolling the percentage and offset are okay, but when I pass the 100% (in the log it reaches 0.99722224) it goes down to 54% and start going up again as I keep scrolling down.

**Comment by kanytu** [comment]
Could you try with release 1.5?

**Comment by facundomedica** [comment]
Okay, I'll do that as soon as I can and get back to you! Thanks!

**Comment by facundomedica** [comment]
Works perfectly, thanks for the fast fix!
