### ISSUE TITLE
percentage's value can read 100.0

### ISSUE THREAD

**Issue by yushilong** [kanytu/android-parallax-recyclerview#44]
02-03 15:50:28.112 28916-28916/com.hupu.shihuo E/alpha: percentage=0.7039338
02-03 15:50:28.112 28916-28916/com.hupu.shihuo E/alpha: 180
02-03 15:50:28.112 28916-28916/com.hupu.shihuo E/hexAlpha: b4
02-03 15:50:28.148 28916-28916/com.hupu.shihuo E/alpha: percentage=0.8688751
02-03 15:50:28.148 28916-28916/com.hupu.shihuo E/alpha: 222
02-03 15:50:28.148 28916-28916/com.hupu.shihuo E/hexAlpha: de
02-03 15:50:28.151 28916-28916/com.hupu.shihuo E/alpha: percentage=0.8730159
02-03 15:50:28.151 28916-28916/com.hupu.shihuo E/alpha: 223
02-03 15:50:28.151 28916-28916/com.hupu.shihuo E/hexAlpha: df
02-03 15:50:28.185 28916-28916/com.hupu.shihuo E/alpha: percentage=0.97722566
02-03 15:50:28.185 28916-28916/com.hupu.shihuo E/alpha: 249
02-03 15:50:28.185 28916-28916/com.hupu.shihuo E/hexAlpha: f9
02-03 15:50:28.210 28916-28916/com.hupu.shihuo E/alpha: percentage=100.0
02-03 15:50:28.210 28916-28916/com.hupu.shihuo E/alpha: 25500
02-03 15:50:28.210 28916-28916/com.hupu.shihuo E/hexAlpha: 639c

percentage 's value shoud be 1.0 at the last!

**Comment by kanytu** [comment]
This is related to #43
